# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaUGRPZJh78xKF0vcffW1fDzzhN78hz_
"""

nome = input('Olá como você se chama? ')
print(nome + ' vamos realizar alguns calculos!')
num1 = int(input('Digite um numero: '))
num2 = int(input('Digite outro numero: '))

def somar(num1, num2):
    return num1 + num2
def subtrair(num1, num2):
    return num1 - num2
def multiplicar(num1, num2):
    return num1 * num2
def dividir(num1, num2):
    return num1 / num2
operacao = input('Agora informa qual operação deseja realizar. (+, -, *, /): ')

if operacao == "+":
  resultado = somar(num1, num2)
elif operacao == "-":
  resultado = subtrair(num1, num2)
elif operacao == "*":
  resultado = multiplicar(num1, num2)
elif operacao == "/":
  resultado = dividir(num1, num2)
print ('O resultado é:', resultado)